name: Check for New OAuth2-Proxy Release

on:
  schedule:
    - cron: '30 3 * * *' # Runs at 03:30 daily
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get latest oauth2-proxy release tag
        id: get_tag
        run: |
          # Fetch latest tag from the official repo
          LATEST_TAG=$(gh api /repos/oauth2-proxy/oauth2-proxy/releases/latest --jq .tag_name)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Check if release tag is new
        id: check
        uses: actions/cache@v5
        with:
          path: .cache
          key: oauth-release-${{ steps.get_tag.outputs.LATEST_TAG }}

      - name: Create cache marker
        if: steps.check.outputs.cache-hit != 'true'
        run: |
          mkdir -p .cache
          echo "${{ steps.get_tag.outputs.LATEST_TAG }}" > .cache/oauth-tag

      - name: Trigger build workflow
        if: steps.check.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # trigger in build-and-push.yml
          event-type: oauth-release